name: Add Type Hints

on: [push, pull_request]

jobs:
  add-type-hints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install monkeytype
          # Add other dependencies if required

      - name: Run MonkeyType to add type hints
        run: python add_type_hints.py

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Commit changes
        env:
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
        run: |
          git add .
          git commit -m 'Add type hints using MonkeyType'
      
      - name: Push changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git remote set-url origin https://${{ secrets.PAT }}@github.com/${{ github.repository }}
          git push origin HEAD:main
