name: isort Import Sorting

on: [push, pull_request]

jobs:
  isort:
    name: Run isort
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install isort
        run: pip install isort

      - name: Run isort
        run: isort --check-only .
