name: Add Type Hints

on: [push, pull_request]

jobs:
  add_type_hints:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: false  # otherwise, the token used is the default GITHUB_TOKEN, instead of the PAT

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy autoflake monkeytype

    - name: Run Tests and Collect Type Information
      run: |
        # Replace 'your_test_script.py' with the actual script to run tests
        monkeytype run your_test_script.py

    - name: Apply Type Hints
      run: |
        for file in $(find src -name '*.py'); do
          module_path=$(echo $file | sed 's|/|.|g' | sed 's|.py||')
          monkeytype apply $module_path
          autoflake --in-place --remove-all-unused-imports --ignore-init-module-imports $file
          mypy --install-types --non-interactive $file
        done

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add src/*.py
        git commit -m "Add type hints using MonkeyType"
        git push origin HEAD:${{ github.ref }}
      env:
        GITHUB_TOKEN: \${{ secrets.PAT }}
