name: Add Type Hints

on: [push, pull_request]

jobs:
  add_type_hints:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy autoflake monkeytype

    - name: Run Tests and Collect Type Information
      env:
        PYTHONPATH: ./src
      run: |
        monkeytype run your_test_script.py

    - name: Debug MonkeyType
      run: |
        echo "MonkeyType SQLite database contents:"
        sqlite3 monkeytype.sqlite3 .dump

    - name: Show Files Before Applying Type Hints
      run: |
        echo "Contents of Python files before applying type hints:"
        find src -name '*.py' -exec cat {} +

    - name: Apply Type Hints
      env:
        PYTHONPATH: ./src
      run: |
        for file in $(find src -name '*.py'); do
          module_path=$(echo $file | sed 's|src/||' | sed 's|/|.|g' | sed 's|.py||')
          echo "Applying type hints to $module_path"
          monkeytype apply $module_path || echo "No traces found for module $module_path"
        done

    - name: Show Files After Applying Type Hints
      run: |
        echo "Contents of Python files after applying type hints:"
        find src -name '*.py' -exec cat {} +

    - name: Run Mypy
      run: |
        mypy src

    - name: Show Mypy Output
      run: |
        echo "Mypy output:"
        mypy src
